/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lasermanager;

/**
 *
 * @author user
 */
public class SequenceTriggerDialog extends javax.swing.JDialog {

    /**
     * Creates new form SequenceTriggerDialog
     */
    public static final int RESULT_OK = 0;
    public static final int RESULT_CANCEL = 1;
    public SequenceTrigger Trigger;

    private int ModalResult;

    public SequenceTriggerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.ModalResult = RESULT_CANCEL;
    }

    public int GetResult() {
        return ModalResult;
    }

    public void SetTrigger(SequenceTrigger trigger) {
        Trigger = trigger;
        ApplyTrigger();
    }

    private void ApplyTrigger() {
        SeqTriggerUsbButton.setSelected(false);
        SeqTriggerTimerButton.setSelected(false);
        SeqTriggerDI1RisingButton.setSelected(false);
        SeqTriggerDI1FallingButton.setSelected(false);
        SeqTriggerDI2RisingButton.setSelected(false);
        SeqTriggerDI2FallingButton.setSelected(false);
        switch (Trigger.Type) {
            case SequenceTrigger.TRIGGER_USB:
                SeqTriggerUsbButton.setSelected(true);
                break;
            case SequenceTrigger.TRIGGER_TIMER:
                SeqTriggerTimerButton.setSelected(true);
                break;
            case SequenceTrigger.TRIGGER_RISING_1:
                SeqTriggerDI1RisingButton.setSelected(true);
                break;
            case SequenceTrigger.TRIGGER_FALLING_1:
                SeqTriggerDI1FallingButton.setSelected(true);
                break;
            case SequenceTrigger.TRIGGER_RISING_2:
                SeqTriggerDI2RisingButton.setSelected(true);
                break;
            case SequenceTrigger.TRIGGER_FALLING_2:
                SeqTriggerDI2FallingButton.setSelected(true);
                break;
        }

        SeqTriggeTimeSpinner.setValue(Trigger.TimerValue / 10.0f);
        SeqTriggeTimeSlider.setValue(Trigger.TimerValue);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeqTriggerUsbPanel = new javax.swing.JPanel();
        SeqTriggerUsbButton = new javax.swing.JToggleButton();
        SeqTriggerTimerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        SeqTriggerTimerButton = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        SeqTriggeTimeSpinner = new javax.swing.JSpinner();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
        jLabel1 = new javax.swing.JLabel();
        SeqTriggeTimeSlider = new javax.swing.JSlider();
        SeqTriggerDI1Panel = new javax.swing.JPanel();
        SeqTriggerDI1RisingButton = new javax.swing.JToggleButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        SeqTriggerDI1FallingButton = new javax.swing.JToggleButton();
        SeqTriggerDI1Panel1 = new javax.swing.JPanel();
        SeqTriggerDI2RisingButton = new javax.swing.JToggleButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        SeqTriggerDI2FallingButton = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        SeqTriggerOkButton = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        SeqTriggerCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Step transition");
        setMaximumSize(new java.awt.Dimension(2700, 2147483647));
        setMinimumSize(new java.awt.Dimension(270, 200));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        SeqTriggerUsbPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 5, 5));
        SeqTriggerUsbPanel.setMaximumSize(new java.awt.Dimension(270, 60));
        SeqTriggerUsbPanel.setMinimumSize(new java.awt.Dimension(270, 60));
        SeqTriggerUsbPanel.setName(""); // NOI18N
        SeqTriggerUsbPanel.setPreferredSize(new java.awt.Dimension(270, 60));
        SeqTriggerUsbPanel.setLayout(new javax.swing.BoxLayout(SeqTriggerUsbPanel, javax.swing.BoxLayout.X_AXIS));

        SeqTriggerUsbButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqTriggerUsbButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lasermanager/images/usb.png"))); // NOI18N
        SeqTriggerUsbButton.setText("USB");
        SeqTriggerUsbButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeqTriggerUsbButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqTriggerUsbButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqTriggerUsbButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqTriggerUsbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqTriggerUsbButtonActionPerformed(evt);
            }
        });
        SeqTriggerUsbPanel.add(SeqTriggerUsbButton);

        getContentPane().add(SeqTriggerUsbPanel);

        SeqTriggerTimerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 5));
        SeqTriggerTimerPanel.setMaximumSize(new java.awt.Dimension(270, 80));
        SeqTriggerTimerPanel.setMinimumSize(new java.awt.Dimension(270, 80));
        SeqTriggerTimerPanel.setName(""); // NOI18N
        SeqTriggerTimerPanel.setPreferredSize(new java.awt.Dimension(270, 80));
        SeqTriggerTimerPanel.setLayout(new javax.swing.BoxLayout(SeqTriggerTimerPanel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(130, 80));
        jPanel1.setMinimumSize(new java.awt.Dimension(130, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(130, 80));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        SeqTriggerTimerButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqTriggerTimerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lasermanager/images/timer.png"))); // NOI18N
        SeqTriggerTimerButton.setText("Timer");
        SeqTriggerTimerButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeqTriggerTimerButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqTriggerTimerButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqTriggerTimerButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqTriggerTimerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqTriggerTimerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SeqTriggerTimerButton);

        SeqTriggerTimerPanel.add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(120, 80));
        jPanel2.setMinimumSize(new java.awt.Dimension(120, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 80));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        SeqTriggeTimeSpinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqTriggeTimeSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.1f), Float.valueOf(0.1f), Float.valueOf(300.0f), Float.valueOf(0.1f)));
        SeqTriggeTimeSpinner.setMinimumSize(new java.awt.Dimension(30, 40));
        SeqTriggeTimeSpinner.setPreferredSize(new java.awt.Dimension(30, 40));
        SeqTriggeTimeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SeqTriggeTimeSpinnerStateChanged(evt);
            }
        });
        jPanel3.add(SeqTriggeTimeSpinner);
        jPanel3.add(filler3);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("s");
        jPanel3.add(jLabel1);

        jPanel2.add(jPanel3);

        SeqTriggeTimeSlider.setMajorTickSpacing(1);
        SeqTriggeTimeSlider.setMaximum(3000);
        SeqTriggeTimeSlider.setMinimum(1);
        SeqTriggeTimeSlider.setMinimumSize(new java.awt.Dimension(36, 40));
        SeqTriggeTimeSlider.setPreferredSize(new java.awt.Dimension(200, 40));
        SeqTriggeTimeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SeqTriggeTimeSliderStateChanged(evt);
            }
        });
        jPanel2.add(SeqTriggeTimeSlider);

        SeqTriggerTimerPanel.add(jPanel2);

        getContentPane().add(SeqTriggerTimerPanel);

        SeqTriggerDI1Panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 5));
        SeqTriggerDI1Panel.setMaximumSize(new java.awt.Dimension(270, 50));
        SeqTriggerDI1Panel.setMinimumSize(new java.awt.Dimension(270, 50));
        SeqTriggerDI1Panel.setPreferredSize(new java.awt.Dimension(270, 50));
        SeqTriggerDI1Panel.setLayout(new javax.swing.BoxLayout(SeqTriggerDI1Panel, javax.swing.BoxLayout.LINE_AXIS));

        SeqTriggerDI1RisingButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqTriggerDI1RisingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lasermanager/images/rising.png"))); // NOI18N
        SeqTriggerDI1RisingButton.setText("DI 1");
        SeqTriggerDI1RisingButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeqTriggerDI1RisingButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqTriggerDI1RisingButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqTriggerDI1RisingButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqTriggerDI1RisingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqTriggerDI1RisingButtonActionPerformed(evt);
            }
        });
        SeqTriggerDI1Panel.add(SeqTriggerDI1RisingButton);
        SeqTriggerDI1Panel.add(filler1);

        SeqTriggerDI1FallingButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqTriggerDI1FallingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lasermanager/images/falling.png"))); // NOI18N
        SeqTriggerDI1FallingButton.setText("DI 1");
        SeqTriggerDI1FallingButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeqTriggerDI1FallingButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqTriggerDI1FallingButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqTriggerDI1FallingButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqTriggerDI1FallingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqTriggerDI1FallingButtonActionPerformed(evt);
            }
        });
        SeqTriggerDI1Panel.add(SeqTriggerDI1FallingButton);

        getContentPane().add(SeqTriggerDI1Panel);

        SeqTriggerDI1Panel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 5));
        SeqTriggerDI1Panel1.setMaximumSize(new java.awt.Dimension(270, 50));
        SeqTriggerDI1Panel1.setMinimumSize(new java.awt.Dimension(270, 50));
        SeqTriggerDI1Panel1.setPreferredSize(new java.awt.Dimension(270, 50));
        SeqTriggerDI1Panel1.setLayout(new javax.swing.BoxLayout(SeqTriggerDI1Panel1, javax.swing.BoxLayout.LINE_AXIS));

        SeqTriggerDI2RisingButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqTriggerDI2RisingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lasermanager/images/rising.png"))); // NOI18N
        SeqTriggerDI2RisingButton.setText("DI 2");
        SeqTriggerDI2RisingButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeqTriggerDI2RisingButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqTriggerDI2RisingButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqTriggerDI2RisingButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqTriggerDI2RisingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqTriggerDI2RisingButtonActionPerformed(evt);
            }
        });
        SeqTriggerDI1Panel1.add(SeqTriggerDI2RisingButton);
        SeqTriggerDI1Panel1.add(filler2);

        SeqTriggerDI2FallingButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqTriggerDI2FallingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lasermanager/images/falling.png"))); // NOI18N
        SeqTriggerDI2FallingButton.setText("DI 2");
        SeqTriggerDI2FallingButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeqTriggerDI2FallingButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqTriggerDI2FallingButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqTriggerDI2FallingButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqTriggerDI2FallingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqTriggerDI2FallingButtonActionPerformed(evt);
            }
        });
        SeqTriggerDI1Panel1.add(SeqTriggerDI2FallingButton);

        getContentPane().add(SeqTriggerDI1Panel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 10, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(270, 70));
        jPanel4.setMinimumSize(new java.awt.Dimension(270, 70));
        jPanel4.setPreferredSize(new java.awt.Dimension(270, 70));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        SeqTriggerOkButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqTriggerOkButton.setText("OK");
        SeqTriggerOkButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqTriggerOkButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqTriggerOkButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqTriggerOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqTriggerOkButtonActionPerformed(evt);
            }
        });
        jPanel4.add(SeqTriggerOkButton);
        jPanel4.add(filler4);

        SeqTriggerCancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqTriggerCancelButton.setText("Cancel");
        SeqTriggerCancelButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqTriggerCancelButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqTriggerCancelButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqTriggerCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqTriggerCancelButtonActionPerformed(evt);
            }
        });
        jPanel4.add(SeqTriggerCancelButton);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeqTriggeTimeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SeqTriggeTimeSliderStateChanged
        float value;
        value = (float) (SeqTriggeTimeSlider.getValue() / 10.0f);
        SeqTriggeTimeSpinner.setValue(value);
        Trigger.TimerValue = SeqTriggeTimeSlider.getValue();
    }//GEN-LAST:event_SeqTriggeTimeSliderStateChanged

    private void SeqTriggeTimeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SeqTriggeTimeSpinnerStateChanged
        int value;
        value = Math.round((float) SeqTriggeTimeSpinner.getValue() * 10.0f);
        Trigger.TimerValue = value;
        SeqTriggeTimeSlider.setValue(value);
    }//GEN-LAST:event_SeqTriggeTimeSpinnerStateChanged

    private void SeqTriggerCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqTriggerCancelButtonActionPerformed
        this.ModalResult = this.RESULT_CANCEL;
        this.setVisible(false);
    }//GEN-LAST:event_SeqTriggerCancelButtonActionPerformed

    private void SeqTriggerOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqTriggerOkButtonActionPerformed
        this.ModalResult = this.RESULT_OK;
        this.setVisible(false);
    }//GEN-LAST:event_SeqTriggerOkButtonActionPerformed

    private void SeqTriggerTimerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqTriggerTimerButtonActionPerformed
        Trigger.Type = SequenceTrigger.TRIGGER_TIMER;
        ApplyTrigger();
    }//GEN-LAST:event_SeqTriggerTimerButtonActionPerformed

    private void SeqTriggerUsbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqTriggerUsbButtonActionPerformed
        Trigger.Type = SequenceTrigger.TRIGGER_USB;
        ApplyTrigger();
    }//GEN-LAST:event_SeqTriggerUsbButtonActionPerformed

    private void SeqTriggerDI1RisingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqTriggerDI1RisingButtonActionPerformed
        Trigger.Type = SequenceTrigger.TRIGGER_RISING_1;
        ApplyTrigger();
    }//GEN-LAST:event_SeqTriggerDI1RisingButtonActionPerformed

    private void SeqTriggerDI1FallingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqTriggerDI1FallingButtonActionPerformed
        Trigger.Type = SequenceTrigger.TRIGGER_FALLING_1;
        ApplyTrigger();
    }//GEN-LAST:event_SeqTriggerDI1FallingButtonActionPerformed

    private void SeqTriggerDI2RisingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqTriggerDI2RisingButtonActionPerformed
        Trigger.Type = SequenceTrigger.TRIGGER_RISING_2;
        ApplyTrigger();
    }//GEN-LAST:event_SeqTriggerDI2RisingButtonActionPerformed

    private void SeqTriggerDI2FallingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqTriggerDI2FallingButtonActionPerformed
        Trigger.Type = SequenceTrigger.TRIGGER_FALLING_2;
        ApplyTrigger();
    }//GEN-LAST:event_SeqTriggerDI2FallingButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SequenceTriggerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SequenceTriggerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SequenceTriggerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SequenceTriggerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SequenceTriggerDialog dialog = new SequenceTriggerDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider SeqTriggeTimeSlider;
    private javax.swing.JSpinner SeqTriggeTimeSpinner;
    private javax.swing.JButton SeqTriggerCancelButton;
    private javax.swing.JToggleButton SeqTriggerDI1FallingButton;
    private javax.swing.JPanel SeqTriggerDI1Panel;
    private javax.swing.JPanel SeqTriggerDI1Panel1;
    private javax.swing.JToggleButton SeqTriggerDI1RisingButton;
    private javax.swing.JToggleButton SeqTriggerDI2FallingButton;
    private javax.swing.JToggleButton SeqTriggerDI2RisingButton;
    private javax.swing.JButton SeqTriggerOkButton;
    private javax.swing.JToggleButton SeqTriggerTimerButton;
    private javax.swing.JPanel SeqTriggerTimerPanel;
    private javax.swing.JToggleButton SeqTriggerUsbButton;
    private javax.swing.JPanel SeqTriggerUsbPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
