/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lasermanager;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author user
 */
public class SequenceAnalogActionDialog extends javax.swing.JDialog {

    /**
     * Creates new form SequenceAnalogActionDialog
     */
    public static final int RESULT_OK = 0;
    public static final int RESULT_CANCEL = 1;

    public AnalogAction Action;
    private int ModalResult;

    private float Factor;

    public SequenceAnalogActionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.ModalResult = RESULT_CANCEL;
    }

    public int GetResult() {
        return ModalResult;
    }

    public void SetActoin(AnalogAction action) {
        Action = action;
        float value = Action.Value;

        SeqAnalogNoChangeButton.setSelected(Action.ActionType == AnalogAction.ACTION_NONE);
        SeqAnalogChangeButton.setSelected(Action.ActionType != AnalogAction.ACTION_NONE);

        if (Action.ValueType == AnalogAction.VALUE_VOLTAGE) {
            Factor = 100.0f;
            SpinnerNumberModel m;
            m = (SpinnerNumberModel) SeqAnalogActionValueSpinner.getModel();
            m.setMinimum(0.0f);
            m.setMaximum(5.0f);
            m.setStepSize(0.01f);
            SeqAnalogActionValueSlider.setMinimum(0);
            SeqAnalogActionValueSlider.setMaximum(500);
            SeqAnalogActionValueLabel.setText("V");
        } else {
            Factor = 10.0f;
            SpinnerNumberModel m;
            m = (SpinnerNumberModel) SeqAnalogActionValueSpinner.getModel();
            m.setMinimum(0.0f);
            m.setMaximum(2000.0f);
            m.setStepSize(0.1f);
            SeqAnalogActionValueSlider.setMinimum(0);
            SeqAnalogActionValueSlider.setMaximum(20000);
            SeqAnalogActionValueLabel.setText("mW");
        }

        Action.Value = value;
        ApplyAction();
    }

    private void ApplyAction() {
        SeqAnalogActionValueSpinner.setValue(Action.Value);
        SeqAnalogActionValueSlider.setValue((int) Math.round(Action.Value * Factor));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeqAnalogNoChangePanel = new javax.swing.JPanel();
        SeqAnalogNoChangeButton = new javax.swing.JToggleButton();
        SeqAnalogChangePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        SeqAnalogChangeButton = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        SeqAnalogActionValueSpinner = new javax.swing.JSpinner();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
        SeqAnalogActionValueLabel = new javax.swing.JLabel();
        SeqAnalogActionValueSlider = new javax.swing.JSlider();
        jPanel4 = new javax.swing.JPanel();
        SeqAnalogActionOkButton = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        SeqAnalogActionCancelButton = new javax.swing.JButton();

        setTitle("Analog Output Action");
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        SeqAnalogNoChangePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 5, 5));
        SeqAnalogNoChangePanel.setMaximumSize(new java.awt.Dimension(270, 60));
        SeqAnalogNoChangePanel.setMinimumSize(new java.awt.Dimension(270, 60));
        SeqAnalogNoChangePanel.setName(""); // NOI18N
        SeqAnalogNoChangePanel.setPreferredSize(new java.awt.Dimension(270, 60));
        SeqAnalogNoChangePanel.setLayout(new javax.swing.BoxLayout(SeqAnalogNoChangePanel, javax.swing.BoxLayout.X_AXIS));

        SeqAnalogNoChangeButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqAnalogNoChangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lasermanager/images/nochange.png"))); // NOI18N
        SeqAnalogNoChangeButton.setText("Keep");
        SeqAnalogNoChangeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeqAnalogNoChangeButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqAnalogNoChangeButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqAnalogNoChangeButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqAnalogNoChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqAnalogNoChangeButtonActionPerformed(evt);
            }
        });
        SeqAnalogNoChangePanel.add(SeqAnalogNoChangeButton);

        getContentPane().add(SeqAnalogNoChangePanel);

        SeqAnalogChangePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 5));
        SeqAnalogChangePanel.setMaximumSize(new java.awt.Dimension(270, 80));
        SeqAnalogChangePanel.setMinimumSize(new java.awt.Dimension(270, 80));
        SeqAnalogChangePanel.setName(""); // NOI18N
        SeqAnalogChangePanel.setPreferredSize(new java.awt.Dimension(270, 80));
        SeqAnalogChangePanel.setLayout(new javax.swing.BoxLayout(SeqAnalogChangePanel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(130, 80));
        jPanel1.setMinimumSize(new java.awt.Dimension(130, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(130, 80));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        SeqAnalogChangeButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqAnalogChangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lasermanager/images/change.png"))); // NOI18N
        SeqAnalogChangeButton.setText("Change");
        SeqAnalogChangeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeqAnalogChangeButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqAnalogChangeButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqAnalogChangeButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqAnalogChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqAnalogChangeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SeqAnalogChangeButton);

        SeqAnalogChangePanel.add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(120, 80));
        jPanel2.setMinimumSize(new java.awt.Dimension(120, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(120, 80));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        SeqAnalogActionValueSpinner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqAnalogActionValueSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.1f), Float.valueOf(0.1f), Float.valueOf(300.0f), Float.valueOf(0.1f)));
        SeqAnalogActionValueSpinner.setMinimumSize(new java.awt.Dimension(30, 40));
        SeqAnalogActionValueSpinner.setPreferredSize(new java.awt.Dimension(30, 40));
        SeqAnalogActionValueSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SeqAnalogActionValueSpinnerStateChanged(evt);
            }
        });
        jPanel3.add(SeqAnalogActionValueSpinner);
        jPanel3.add(filler3);

        SeqAnalogActionValueLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqAnalogActionValueLabel.setText("s");
        jPanel3.add(SeqAnalogActionValueLabel);

        jPanel2.add(jPanel3);

        SeqAnalogActionValueSlider.setMajorTickSpacing(1);
        SeqAnalogActionValueSlider.setMaximum(3000);
        SeqAnalogActionValueSlider.setMinimum(1);
        SeqAnalogActionValueSlider.setMinimumSize(new java.awt.Dimension(36, 40));
        SeqAnalogActionValueSlider.setPreferredSize(new java.awt.Dimension(200, 40));
        SeqAnalogActionValueSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SeqAnalogActionValueSliderStateChanged(evt);
            }
        });
        jPanel2.add(SeqAnalogActionValueSlider);

        SeqAnalogChangePanel.add(jPanel2);

        getContentPane().add(SeqAnalogChangePanel);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 10, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(270, 70));
        jPanel4.setMinimumSize(new java.awt.Dimension(270, 70));
        jPanel4.setPreferredSize(new java.awt.Dimension(270, 70));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        SeqAnalogActionOkButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqAnalogActionOkButton.setText("OK");
        SeqAnalogActionOkButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqAnalogActionOkButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqAnalogActionOkButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqAnalogActionOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqAnalogActionOkButtonActionPerformed(evt);
            }
        });
        jPanel4.add(SeqAnalogActionOkButton);
        jPanel4.add(filler4);

        SeqAnalogActionCancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqAnalogActionCancelButton.setText("Cancel");
        SeqAnalogActionCancelButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqAnalogActionCancelButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqAnalogActionCancelButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqAnalogActionCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqAnalogActionCancelButtonActionPerformed(evt);
            }
        });
        jPanel4.add(SeqAnalogActionCancelButton);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeqAnalogActionOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqAnalogActionOkButtonActionPerformed
        this.ModalResult = this.RESULT_OK;
        this.setVisible(false);
    }//GEN-LAST:event_SeqAnalogActionOkButtonActionPerformed

    private void SeqAnalogActionCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqAnalogActionCancelButtonActionPerformed
        this.ModalResult = this.RESULT_CANCEL;
        this.setVisible(false);
    }//GEN-LAST:event_SeqAnalogActionCancelButtonActionPerformed

    private void SeqAnalogActionValueSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SeqAnalogActionValueSpinnerStateChanged
        int value;
        value = (int) Math.round((float) SeqAnalogActionValueSpinner.getValue() * Factor);
        SeqAnalogActionValueSlider.setValue(value);
        Action.Value = (float) SeqAnalogActionValueSpinner.getValue();
    }//GEN-LAST:event_SeqAnalogActionValueSpinnerStateChanged

    private void SeqAnalogActionValueSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SeqAnalogActionValueSliderStateChanged
        float value;
        value = (float) (SeqAnalogActionValueSlider.getValue() / Factor);
        SeqAnalogActionValueSpinner.setValue(value);
        Action.Value = (float) SeqAnalogActionValueSpinner.getValue();
    }//GEN-LAST:event_SeqAnalogActionValueSliderStateChanged

    private void SeqAnalogNoChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqAnalogNoChangeButtonActionPerformed
        SeqAnalogNoChangeButton.setSelected(true);
        SeqAnalogChangeButton.setSelected(false);
        Action.ActionType = AnalogAction.ACTION_NONE;
    }//GEN-LAST:event_SeqAnalogNoChangeButtonActionPerformed

    private void SeqAnalogChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqAnalogChangeButtonActionPerformed
        SeqAnalogNoChangeButton.setSelected(false);
        SeqAnalogChangeButton.setSelected(true);
        Action.ActionType = AnalogAction.ACTION_CHANGE;
    }//GEN-LAST:event_SeqAnalogChangeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SequenceAnalogActionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SequenceAnalogActionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SequenceAnalogActionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SequenceAnalogActionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SequenceAnalogActionDialog dialog = new SequenceAnalogActionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SeqAnalogActionCancelButton;
    private javax.swing.JButton SeqAnalogActionOkButton;
    private javax.swing.JLabel SeqAnalogActionValueLabel;
    private javax.swing.JSlider SeqAnalogActionValueSlider;
    private javax.swing.JSpinner SeqAnalogActionValueSpinner;
    private javax.swing.JToggleButton SeqAnalogChangeButton;
    private javax.swing.JPanel SeqAnalogChangePanel;
    private javax.swing.JToggleButton SeqAnalogNoChangeButton;
    private javax.swing.JPanel SeqAnalogNoChangePanel;
    private javax.swing.JToggleButton SeqTriggerUsbButton;
    private javax.swing.JPanel SeqTriggerUsbPanel;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
