/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lasermanager;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author user
 */
public class SequenceDigitalActionDialog extends javax.swing.JDialog {

    /**
     * Creates new form SequenceAnalogActionDialog
     */
    public static final int RESULT_OK = 0;
    public static final int RESULT_CANCEL = 1;

    public DigitalAction Action;
    private int ModalResult;

    private float Factor;

    public SequenceDigitalActionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.ModalResult = RESULT_CANCEL;
    }

    public int GetResult() {
        return ModalResult;
    }

    public void SetActoin(DigitalAction action) {
        Action = action;

        SeqDigitalNoChangeButton.setSelected(Action.ActionType == DigitalAction.ACTION_NONE);
        SeqDigitalOnButton.setSelected(Action.ActionType == DigitalAction.ACTION_ON);
        SeqDigitalOffButton.setSelected(Action.ActionType == DigitalAction.ACTION_OFF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeqDigitalNoChangePanel = new javax.swing.JPanel();
        SeqDigitalNoChangeButton = new javax.swing.JToggleButton();
        SeqDigitalOnPanel = new javax.swing.JPanel();
        SeqDigitalOnButton = new javax.swing.JToggleButton();
        SeqDigitalOffPanel = new javax.swing.JPanel();
        SeqDigitalOffButton = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        SeqAnalogActionOkButton = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        SeqAnalogActionCancelButton = new javax.swing.JButton();

        setTitle("Analog Output Action");
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        SeqDigitalNoChangePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 5, 5));
        SeqDigitalNoChangePanel.setMaximumSize(new java.awt.Dimension(270, 60));
        SeqDigitalNoChangePanel.setMinimumSize(new java.awt.Dimension(270, 60));
        SeqDigitalNoChangePanel.setName(""); // NOI18N
        SeqDigitalNoChangePanel.setPreferredSize(new java.awt.Dimension(270, 60));
        SeqDigitalNoChangePanel.setLayout(new javax.swing.BoxLayout(SeqDigitalNoChangePanel, javax.swing.BoxLayout.X_AXIS));

        SeqDigitalNoChangeButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqDigitalNoChangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lasermanager/images/nochange.png"))); // NOI18N
        SeqDigitalNoChangeButton.setText("Keep");
        SeqDigitalNoChangeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeqDigitalNoChangeButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqDigitalNoChangeButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqDigitalNoChangeButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqDigitalNoChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqDigitalNoChangeButtonActionPerformed(evt);
            }
        });
        SeqDigitalNoChangePanel.add(SeqDigitalNoChangeButton);

        getContentPane().add(SeqDigitalNoChangePanel);

        SeqDigitalOnPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 5));
        SeqDigitalOnPanel.setMaximumSize(new java.awt.Dimension(270, 50));
        SeqDigitalOnPanel.setMinimumSize(new java.awt.Dimension(270, 50));
        SeqDigitalOnPanel.setName(""); // NOI18N
        SeqDigitalOnPanel.setPreferredSize(new java.awt.Dimension(270, 50));
        SeqDigitalOnPanel.setLayout(new javax.swing.BoxLayout(SeqDigitalOnPanel, javax.swing.BoxLayout.X_AXIS));

        SeqDigitalOnButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqDigitalOnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lasermanager/images/rising.png"))); // NOI18N
        SeqDigitalOnButton.setText("On");
        SeqDigitalOnButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeqDigitalOnButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqDigitalOnButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqDigitalOnButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqDigitalOnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqDigitalOnButtonActionPerformed(evt);
            }
        });
        SeqDigitalOnPanel.add(SeqDigitalOnButton);

        getContentPane().add(SeqDigitalOnPanel);

        SeqDigitalOffPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 5));
        SeqDigitalOffPanel.setMaximumSize(new java.awt.Dimension(270, 50));
        SeqDigitalOffPanel.setMinimumSize(new java.awt.Dimension(270, 50));
        SeqDigitalOffPanel.setName(""); // NOI18N
        SeqDigitalOffPanel.setPreferredSize(new java.awt.Dimension(270, 50));
        SeqDigitalOffPanel.setLayout(new javax.swing.BoxLayout(SeqDigitalOffPanel, javax.swing.BoxLayout.X_AXIS));

        SeqDigitalOffButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqDigitalOffButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lasermanager/images/falling.png"))); // NOI18N
        SeqDigitalOffButton.setText("Off");
        SeqDigitalOffButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SeqDigitalOffButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqDigitalOffButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqDigitalOffButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqDigitalOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqDigitalOffButtonActionPerformed(evt);
            }
        });
        SeqDigitalOffPanel.add(SeqDigitalOffButton);

        getContentPane().add(SeqDigitalOffPanel);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 10, 10, 0));
        jPanel4.setMaximumSize(new java.awt.Dimension(270, 70));
        jPanel4.setMinimumSize(new java.awt.Dimension(270, 70));
        jPanel4.setPreferredSize(new java.awt.Dimension(270, 70));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        SeqAnalogActionOkButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqAnalogActionOkButton.setText("OK");
        SeqAnalogActionOkButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqAnalogActionOkButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqAnalogActionOkButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqAnalogActionOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqAnalogActionOkButtonActionPerformed(evt);
            }
        });
        jPanel4.add(SeqAnalogActionOkButton);
        jPanel4.add(filler4);

        SeqAnalogActionCancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SeqAnalogActionCancelButton.setText("Cancel");
        SeqAnalogActionCancelButton.setMaximumSize(new java.awt.Dimension(120, 40));
        SeqAnalogActionCancelButton.setMinimumSize(new java.awt.Dimension(120, 40));
        SeqAnalogActionCancelButton.setPreferredSize(new java.awt.Dimension(120, 40));
        SeqAnalogActionCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeqAnalogActionCancelButtonActionPerformed(evt);
            }
        });
        jPanel4.add(SeqAnalogActionCancelButton);

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeqAnalogActionOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqAnalogActionOkButtonActionPerformed
        this.ModalResult = this.RESULT_OK;
        this.setVisible(false);
    }//GEN-LAST:event_SeqAnalogActionOkButtonActionPerformed

    private void SeqAnalogActionCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqAnalogActionCancelButtonActionPerformed
        this.ModalResult = this.RESULT_CANCEL;
        this.setVisible(false);
    }//GEN-LAST:event_SeqAnalogActionCancelButtonActionPerformed

    private void SeqDigitalNoChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqDigitalNoChangeButtonActionPerformed
        SeqDigitalNoChangeButton.setSelected(true);
        SeqDigitalOffButton.setSelected(false);
        SeqDigitalOnButton.setSelected(false);
        Action.ActionType = DigitalAction.ACTION_NONE;
    }//GEN-LAST:event_SeqDigitalNoChangeButtonActionPerformed

    private void SeqDigitalOnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqDigitalOnButtonActionPerformed
        SeqDigitalNoChangeButton.setSelected(false);
        SeqDigitalOffButton.setSelected(false);
        SeqDigitalOnButton.setSelected(true);
        Action.ActionType = DigitalAction.ACTION_ON;
    }//GEN-LAST:event_SeqDigitalOnButtonActionPerformed

    private void SeqDigitalOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeqDigitalOffButtonActionPerformed
        SeqDigitalNoChangeButton.setSelected(false);
        SeqDigitalOffButton.setSelected(true);
        SeqDigitalOnButton.setSelected(false);
        Action.ActionType = DigitalAction.ACTION_OFF;
    }//GEN-LAST:event_SeqDigitalOffButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SequenceDigitalActionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SequenceDigitalActionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SequenceDigitalActionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SequenceDigitalActionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SequenceDigitalActionDialog dialog = new SequenceDigitalActionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SeqAnalogActionCancelButton;
    private javax.swing.JButton SeqAnalogActionOkButton;
    private javax.swing.JToggleButton SeqDigitalNoChangeButton;
    private javax.swing.JPanel SeqDigitalNoChangePanel;
    private javax.swing.JToggleButton SeqDigitalOffButton;
    private javax.swing.JPanel SeqDigitalOffPanel;
    private javax.swing.JToggleButton SeqDigitalOnButton;
    private javax.swing.JPanel SeqDigitalOnPanel;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
